.PHONY: start load check purchases access all test stop reset

start:
	./scripts/01-start-cluster.sh

load:
	./scripts/02-load-data.sh

check:
	./scripts/03-check-data.sh

purchases:
	./scripts/04-run-purchases.sh

access:
	./scripts/05-run-access-log.sh

all:
	./scripts/06-run-all.sh

test:
	./scripts/09-local-tests.sh

stop:
	./scripts/07-stop-cluster.sh

reset:
	./scripts/08-reset-all.sh
